name = "AssignOnce"
uuid = "16b04b15-4d3d-564a-9f8d-460bd0553239"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.1"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
